Repository brycemara/refactor-tractor, pull requests merged in 2020-10, with the labels that each got.

#31 Refactor/activity
  src/Activity.js
  test/activity-test.js
  test/sleep-test.js
Labels: refactor

#33 Add refactor of scripts.js
  package-lock.json
  package.json
  src/Sleep.js
  src/scripts.js
Labels: refactor

#38 Refactor/accessibility
  src/index.html
  src/scripts.js
Labels: refactor

#42 Feature/naming conventions
  src/Activity.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/User.js
  src/scripts.js
Labels: documentation

#48 Refactor/methods
  src/Activity.js
  src/Sleep.js
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/userrepo-test.js
Labels: bug, documentation
